// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PawfectMatch.Data;

#nullable disable

namespace PawfectMatch.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250714143152_Productos Tabs fix1")]
    partial class ProductosTabsfix1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PawfectMatch.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PawfectMatch.Models.Adopciones.AdoptantesDetalles", b =>
                {
                    b.Property<int>("AdoptantesDetallesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdoptantesDetallesID"));

                    b.Property<int?>("HorasAusentes")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NotasJardin")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NotasOtrasMascotas")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PersonasID")
                        .HasColumnType("int");

                    b.Property<string>("RazonAdopcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TieneJardin")
                        .HasColumnType("bit");

                    b.Property<bool>("TieneOtrasMascotas")
                        .HasColumnType("bit");

                    b.Property<int?>("TipoViviendasID")
                        .HasColumnType("int");

                    b.Property<bool>("ViveEnViviendaAlquilada")
                        .HasColumnType("bit");

                    b.HasKey("AdoptantesDetallesID");

                    b.HasIndex("PersonasID");

                    b.HasIndex("TipoViviendasID");

                    b.ToTable("AdoptantesDetalles");
                });

            modelBuilder.Entity("PawfectMatch.Models.Adopciones.EstadoMascota", b =>
                {
                    b.Property<int>("EstadoMascotaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoMascotaID"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EstadoMascotaID");

                    b.ToTable("EstadoMascota");

                    b.HasData(
                        new
                        {
                            EstadoMascotaID = 1,
                            IsDeleted = false,
                            Nombre = "Sano"
                        },
                        new
                        {
                            EstadoMascotaID = 2,
                            IsDeleted = false,
                            Nombre = "Enfermo"
                        });
                });

            modelBuilder.Entity("PawfectMatch.Models.Adopciones.HistorialAdopciones", b =>
                {
                    b.Property<int>("HistorialAdopcionesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistorialAdopcionesID"));

                    b.Property<DateTime>("FechaAdopcion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MascotasAdopcionID")
                        .HasColumnType("int");

                    b.Property<string>("Notas")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SolicitudesAdopcionesID")
                        .HasColumnType("int");

                    b.Property<int?>("SolicitudesAdopcionesID1")
                        .HasColumnType("int");

                    b.HasKey("HistorialAdopcionesID");

                    b.HasIndex("MascotasAdopcionID");

                    b.HasIndex("SolicitudesAdopcionesID");

                    b.HasIndex("SolicitudesAdopcionesID1");

                    b.ToTable("HistorialAdopciones");
                });

            modelBuilder.Entity("PawfectMatch.Models.Adopciones.MascotasAdopcion", b =>
                {
                    b.Property<int>("MascotasAdopcionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MascotasAdopcionID"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("EspeciesID")
                        .HasColumnType("int");

                    b.Property<int>("EstadoID")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("FotoURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RazasID")
                        .HasColumnType("int");

                    b.Property<int>("RelacionSizeID")
                        .HasColumnType("int");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int?>("Tamanio")
                        .HasColumnType("int");

                    b.HasKey("MascotasAdopcionID");

                    b.HasIndex("EspeciesID");

                    b.HasIndex("EstadoID");

                    b.HasIndex("RazasID");

                    b.HasIndex("RelacionSizeID");

                    b.ToTable("MascotasAdopcion");

                    b.HasData(
                        new
                        {
                            MascotasAdopcionID = 1,
                            Descripcion = "Cachorrita juguetona y muy cariñosa con niños.",
                            EstadoID = 2,
                            FechaNacimiento = new DateOnly(2023, 5, 10),
                            FotoURL = "https://images.unsplash.com/photo-1583511655826-05700d52f4ae",
                            IsDeleted = false,
                            Nombre = "Luna",
                            RazasID = 1,
                            RelacionSizeID = 1,
                            Sexo = "f",
                            Tamanio = 1
                        },
                        new
                        {
                            MascotasAdopcionID = 2,
                            Descripcion = "Perro guardián y muy leal. Ideal para casas grandes.",
                            EstadoID = 2,
                            FechaNacimiento = new DateOnly(2022, 11, 15),
                            FotoURL = "https://images.unsplash.com/photo-1601758123927-196f76f75097",
                            IsDeleted = false,
                            Nombre = "Rocky",
                            RazasID = 2,
                            RelacionSizeID = 2,
                            Sexo = "m",
                            Tamanio = 2
                        },
                        new
                        {
                            MascotasAdopcionID = 3,
                            Descripcion = "Gatita rescatada muy tranquila y sociable.",
                            EstadoID = 2,
                            FechaNacimiento = new DateOnly(2024, 2, 1),
                            FotoURL = "https://images.unsplash.com/photo-1592194996308-7b43878e84a6",
                            IsDeleted = false,
                            Nombre = "Mia",
                            RazasID = 3,
                            RelacionSizeID = 1,
                            Sexo = "f",
                            Tamanio = 3
                        },
                        new
                        {
                            MascotasAdopcionID = 4,
                            Descripcion = "Perro fuerte, entrenado y excelente para seguridad.",
                            EstadoID = 2,
                            FechaNacimiento = new DateOnly(2021, 8, 20),
                            FotoURL = "https://images.unsplash.com/photo-1583511655826-05700d52f4ae",
                            IsDeleted = false,
                            Nombre = "Zeus",
                            RazasID = 2,
                            RelacionSizeID = 3,
                            Sexo = "m",
                            Tamanio = 5
                        },
                        new
                        {
                            MascotasAdopcionID = 5,
                            Descripcion = "Muy energética y necesita mucho ejercicio diario.",
                            EstadoID = 2,
                            FechaNacimiento = new DateOnly(2023, 1, 30),
                            FotoURL = "https://images.unsplash.com/photo-1601758003122-58eacb8e3ed1",
                            IsDeleted = false,
                            Nombre = "Nala",
                            RazasID = 1,
                            RelacionSizeID = 2,
                            Sexo = "f",
                            Tamanio = 5
                        },
                        new
                        {
                            MascotasAdopcionID = 6,
                            Descripcion = "Gatito curioso y muy juguetón.",
                            EstadoID = 2,
                            FechaNacimiento = new DateOnly(2024, 4, 15),
                            FotoURL = "https://images.unsplash.com/photo-1592194996308-7b43878e84a6",
                            IsDeleted = false,
                            Nombre = "Simba",
                            RazasID = 3,
                            RelacionSizeID = 1,
                            Sexo = "m",
                            Tamanio = 2
                        },
                        new
                        {
                            MascotasAdopcionID = 7,
                            Descripcion = "Gran danés amoroso y obediente.",
                            EstadoID = 2,
                            FechaNacimiento = new DateOnly(2022, 6, 18),
                            FotoURL = "https://images.unsplash.com/photo-1583511655826-05700d52f4ae",
                            IsDeleted = false,
                            Nombre = "Thor",
                            RazasID = 2,
                            RelacionSizeID = 3,
                            Sexo = "m",
                            Tamanio = 4
                        },
                        new
                        {
                            MascotasAdopcionID = 8,
                            Descripcion = "Gatita blanca, ideal para compañía.",
                            EstadoID = 2,
                            FechaNacimiento = new DateOnly(2023, 7, 9),
                            FotoURL = "https://images.unsplash.com/photo-1580377969203-4ec1eac6d5fe",
                            IsDeleted = false,
                            Nombre = "Lili",
                            RazasID = 3,
                            RelacionSizeID = 1,
                            Sexo = "f",
                            Tamanio = 5
                        },
                        new
                        {
                            MascotasAdopcionID = 9,
                            Descripcion = "Obediente y perfecto para familias con niños.",
                            EstadoID = 2,
                            FechaNacimiento = new DateOnly(2021, 9, 12),
                            FotoURL = "https://images.unsplash.com/photo-1558788353-f76d92427f16",
                            IsDeleted = false,
                            Nombre = "Max",
                            RazasID = 1,
                            RelacionSizeID = 2,
                            Sexo = "m",
                            Tamanio = 5
                        },
                        new
                        {
                            MascotasAdopcionID = 10,
                            Descripcion = "Gatita siamesa muy elegante.",
                            EstadoID = 2,
                            FechaNacimiento = new DateOnly(2024, 3, 22),
                            FotoURL = "https://images.unsplash.com/photo-1574158622682-e40e69881006",
                            IsDeleted = false,
                            Nombre = "Cleo",
                            RazasID = 3,
                            RelacionSizeID = 1,
                            Sexo = "f",
                            Tamanio = 4
                        });
                });

            modelBuilder.Entity("PawfectMatch.Models.Adopciones.Sugerencias", b =>
                {
                    b.Property<int>("SugerenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SugerenciaId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SugerenciaId");

                    b.ToTable("Sugerencias");
                });

            modelBuilder.Entity("PawfectMatch.Models.Adopciones._Presentacion.Diapositivas", b =>
                {
                    b.Property<int>("DiapositivaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiapositivaId"));

                    b.Property<string>("Animacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsButtonLeftActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsButtonRightActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTituloLeftActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTituloRightActive")
                        .HasColumnType("bit");

                    b.Property<string>("LinkButton_Left")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkButton_Right")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("SubTitulo_Left")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTitulo_Right")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextButton_Left")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextButton_Right")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo_Left")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo_Right")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DiapositivaId");

                    b.ToTable("Diapositivas");
                });

            modelBuilder.Entity("PawfectMatch.Models.Adopciones._Presentacion.Presentaciones", b =>
                {
                    b.Property<int>("PresentacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PresentacionId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsActiva")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PresentacionId");

                    b.ToTable("Presentaciones");
                });

            modelBuilder.Entity("PawfectMatch.Models.Adopciones._Presentacion.PresentacionesDiapositivas", b =>
                {
                    b.Property<int>("PresentacionDiapositivaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PresentacionDiapositivaId"));

                    b.Property<int>("DiapositivaId")
                        .HasColumnType("int");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<int>("PresentacionId")
                        .HasColumnType("int");

                    b.HasKey("PresentacionDiapositivaId");

                    b.HasIndex("DiapositivaId");

                    b.HasIndex("PresentacionId");

                    b.ToTable("PresentacionesDiapositivas");
                });

            modelBuilder.Entity("PawfectMatch.Models.Citas", b =>
                {
                    b.Property<int>("CitasID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CitasID"));

                    b.Property<int>("EstadosCitasID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MascotasPersonasID")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PersonasID")
                        .HasColumnType("int");

                    b.HasKey("CitasID");

                    b.HasIndex("EstadosCitasID");

                    b.HasIndex("MascotasPersonasID");

                    b.HasIndex("PersonasID");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("PawfectMatch.Models.ConfiguracionEmpresa", b =>
                {
                    b.Property<int>("EmpresaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpresaID"));

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RNC")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("EmpresaID");

                    b.ToTable("ConfiguracionEmpresa");

                    b.HasData(
                        new
                        {
                            EmpresaID = 1,
                            Direccion = "Av. Principal 123, Ciudad",
                            Nombre = "Veterinaria PawfectMatch",
                            RNC = "101000099",
                            Telefono = "809-123-4567"
                        });
                });

            modelBuilder.Entity("PawfectMatch.Models.Especies", b =>
                {
                    b.Property<int>("EspeciesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EspeciesID"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EspeciesID");

                    b.ToTable("Especies");

                    b.HasData(
                        new
                        {
                            EspeciesID = 1,
                            IsDeleted = false,
                            Nombre = "Gato"
                        },
                        new
                        {
                            EspeciesID = 2,
                            IsDeleted = false,
                            Nombre = "Perro"
                        });
                });

            modelBuilder.Entity("PawfectMatch.Models.EstadoSolicitud", b =>
                {
                    b.Property<int>("EstadoSolicitudID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoSolicitudID"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EstadoSolicitudID");

                    b.ToTable("EstadoSolicitud");

                    b.HasData(
                        new
                        {
                            EstadoSolicitudID = 1,
                            IsDeleted = false,
                            Nombre = "Aprobada"
                        },
                        new
                        {
                            EstadoSolicitudID = 2,
                            IsDeleted = false,
                            Nombre = "En Revisi�n"
                        },
                        new
                        {
                            EstadoSolicitudID = 3,
                            IsDeleted = false,
                            Nombre = "Rechazada"
                        },
                        new
                        {
                            EstadoSolicitudID = 4,
                            IsDeleted = false,
                            Nombre = "En Espera"
                        });
                });

            modelBuilder.Entity("PawfectMatch.Models.Estados", b =>
                {
                    b.Property<int>("EstadoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoID"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EstadoID");

                    b.ToTable("Estados");

                    b.HasData(
                        new
                        {
                            EstadoID = 1,
                            IsDeleted = false,
                            Nombre = "Adoptado"
                        },
                        new
                        {
                            EstadoID = 2,
                            IsDeleted = false,
                            Nombre = "Disponible"
                        },
                        new
                        {
                            EstadoID = 3,
                            IsDeleted = false,
                            Nombre = "No Disponible"
                        });
                });

            modelBuilder.Entity("PawfectMatch.Models.EstadosCitas", b =>
                {
                    b.Property<int>("EstadosCitasID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadosCitasID"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EstadosCitasID");

                    b.ToTable("EstadosCitas");

                    b.HasData(
                        new
                        {
                            EstadosCitasID = 1,
                            IsDeleted = false,
                            Nombre = "Pendiente"
                        },
                        new
                        {
                            EstadosCitasID = 2,
                            IsDeleted = false,
                            Nombre = "Confirmada"
                        },
                        new
                        {
                            EstadosCitasID = 3,
                            IsDeleted = false,
                            Nombre = "Cancelada"
                        });
                });

            modelBuilder.Entity("PawfectMatch.Models.HistoriasClinicas", b =>
                {
                    b.Property<int>("HistoriasClinicaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoriasClinicaID"));

                    b.Property<string>("DescripcionVisita")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Diagnostico")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MascotasPersonasID")
                        .HasColumnType("int");

                    b.Property<int>("PersonasID")
                        .HasColumnType("int");

                    b.Property<string>("Tratamiento")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("HistoriasClinicaID");

                    b.HasIndex("MascotasPersonasID");

                    b.HasIndex("PersonasID");

                    b.ToTable("HistoriasClinicas");
                });

            modelBuilder.Entity("PawfectMatch.Models.POS.CategoriasProductos", b =>
                {
                    b.Property<int>("CategoriasProductosID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriasProductosID"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoriasProductosID");

                    b.ToTable("CategoriasProductos");

                    b.HasData(
                        new
                        {
                            CategoriasProductosID = 1,
                            IsDeleted = false,
                            Nombre = "Alimentos"
                        },
                        new
                        {
                            CategoriasProductosID = 2,
                            IsDeleted = false,
                            Nombre = "Accesorios"
                        });
                });

            modelBuilder.Entity("PawfectMatch.Models.POS.DetallesFacturas", b =>
                {
                    b.Property<int>("DetallesFacturasID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetallesFacturasID"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("FacturasID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TiposItemsID")
                        .HasColumnType("int");

                    b.HasKey("DetallesFacturasID");

                    b.HasIndex("FacturasID");

                    b.HasIndex("TiposItemsID");

                    b.ToTable("DetalleFacturas");
                });

            modelBuilder.Entity("PawfectMatch.Models.POS.EstadosPagos", b =>
                {
                    b.Property<int>("EstadosPagosID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadosPagosID"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EstadosPagosID");

                    b.ToTable("EstadosPagos");

                    b.HasData(
                        new
                        {
                            EstadosPagosID = 1,
                            IsDeleted = false,
                            Nombre = "Pagado"
                        },
                        new
                        {
                            EstadosPagosID = 2,
                            IsDeleted = false,
                            Nombre = "Pendiente"
                        });
                });

            modelBuilder.Entity("PawfectMatch.Models.POS.Facturas", b =>
                {
                    b.Property<int>("FacturasID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacturasID"));

                    b.Property<int>("EstadoPagoID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PersonasID")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("FacturasID");

                    b.HasIndex("EstadoPagoID");

                    b.HasIndex("PersonasID");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("PawfectMatch.Models.POS.Pagos", b =>
                {
                    b.Property<int>("PagosID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PagosID"));

                    b.Property<int>("FacturasID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PagosID");

                    b.HasIndex("FacturasID");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("PawfectMatch.Models.POS.Productos", b =>
                {
                    b.Property<int>("ProductosID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductosID"));

                    b.Property<int>("CategoriasProductosID")
                        .HasColumnType("int");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProveedoresID")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductosID");

                    b.HasIndex("CategoriasProductosID");

                    b.HasIndex("ProveedoresID");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            ProductosID = 1,
                            CategoriasProductosID = 1,
                            Costo = 10.00m,
                            Descripcion = "Croquetas nutritivas para perros adultos.",
                            ImagenUrl = "https://images.rawpixel.com/image_800/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIyLTExL3BmLXMxMDgtcG0tNDExMy1tb2NrdXAuanBn.jpg",
                            IsDeleted = false,
                            Nombre = "Croquetas Premium",
                            Precio = 18.99m,
                            ProveedoresID = 1,
                            Stock = 50
                        },
                        new
                        {
                            ProductosID = 2,
                            CategoriasProductosID = 1,
                            Costo = 2.50m,
                            Descripcion = "Lata de comida gourmet para gatos exigentes.",
                            ImagenUrl = "https://images.rawpixel.com/image_800/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIyLTExL3BmLXMxMDgtcG0tNDExMy1tb2NrdXAuanBn.jpg",
                            IsDeleted = false,
                            Nombre = "Comida Húmeda para Gato",
                            Precio = 4.99m,
                            ProveedoresID = 1,
                            Stock = 100
                        },
                        new
                        {
                            ProductosID = 3,
                            CategoriasProductosID = 2,
                            Costo = 15.00m,
                            Descripcion = "Collar rastreador para mascotas medianas.",
                            ImagenUrl = "https://images.rawpixel.com/image_800/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIyLTExL3BmLXMxMDgtcG0tNDExMy1tb2NrdXAuanBn.jpg",
                            IsDeleted = false,
                            Nombre = "Collar con GPS",
                            Precio = 29.99m,
                            ProveedoresID = 1,
                            Stock = 25
                        },
                        new
                        {
                            ProductosID = 4,
                            CategoriasProductosID = 2,
                            Costo = 12.00m,
                            Descripcion = "Cama acolchonada ideal para gatos y perros pequeños.",
                            ImagenUrl = "https://images.rawpixel.com/image_800/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIyLTExL3BmLXMxMDgtcG0tNDExMy1tb2NrdXAuanBn.jpg",
                            IsDeleted = false,
                            Nombre = "Cama para Mascotas",
                            Precio = 24.99m,
                            ProveedoresID = 1,
                            Stock = 30
                        },
                        new
                        {
                            ProductosID = 5,
                            CategoriasProductosID = 1,
                            Costo = 3.00m,
                            Descripcion = "Galletas orgánicas para entrenamiento.",
                            ImagenUrl = "https://images.rawpixel.com/image_800/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIyLTExL3BmLXMxMDgtcG0tNDExMy1tb2NrdXAuanBn.jpg",
                            IsDeleted = false,
                            Nombre = "Snack Natural",
                            Precio = 6.50m,
                            ProveedoresID = 1,
                            Stock = 80
                        },
                        new
                        {
                            ProductosID = 6,
                            CategoriasProductosID = 2,
                            Costo = 1.80m,
                            Descripcion = "Pelota para perros que emite sonidos al morderla.",
                            ImagenUrl = "https://images.rawpixel.com/image_800/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIyLTExL3BmLXMxMDgtcG0tNDExMy1tb2NrdXAuanBn.jpg",
                            IsDeleted = false,
                            Nombre = "Juguete Pelota Sonora",
                            Precio = 4.00m,
                            ProveedoresID = 1,
                            Stock = 60
                        },
                        new
                        {
                            ProductosID = 7,
                            CategoriasProductosID = 1,
                            Costo = 5.00m,
                            Descripcion = "Suplemento lácteo para crías sin madre.",
                            ImagenUrl = "https://images.rawpixel.com/image_800/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIyLTExL3BmLXMxMDgtcG0tNDExMy1tb2NrdXAuanBn.jpg",
                            IsDeleted = false,
                            Nombre = "Leche para Cachorros",
                            Precio = 9.99m,
                            ProveedoresID = 1,
                            Stock = 45
                        },
                        new
                        {
                            ProductosID = 8,
                            CategoriasProductosID = 2,
                            Costo = 6.00m,
                            Descripcion = "Correa extensible hasta 5 metros.",
                            ImagenUrl = "https://images.rawpixel.com/image_800/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIyLTExL3BmLXMxMDgtcG0tNDExMy1tb2NrdXAuanBn.jpg",
                            IsDeleted = false,
                            Nombre = "Correa Retráctil",
                            Precio = 12.99m,
                            ProveedoresID = 1,
                            Stock = 40
                        },
                        new
                        {
                            ProductosID = 9,
                            CategoriasProductosID = 2,
                            Costo = 8.00m,
                            Descripcion = "Rascador vertical de sisal natural.",
                            ImagenUrl = "https://images.rawpixel.com/image_800/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIyLTExL3BmLXMxMDgtcG0tNDExMy1tb2NrdXAuanBn.jpg",
                            IsDeleted = false,
                            Nombre = "Rascador para Gato",
                            Precio = 15.50m,
                            ProveedoresID = 1,
                            Stock = 20
                        },
                        new
                        {
                            ProductosID = 10,
                            CategoriasProductosID = 1,
                            Costo = 4.00m,
                            Descripcion = "Complemento vitamínico para perros y gatos.",
                            ImagenUrl = "https://images.rawpixel.com/image_800/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIyLTExL3BmLXMxMDgtcG0tNDExMy1tb2NrdXAuanBn.jpg",
                            IsDeleted = false,
                            Nombre = "Vitaminas para Mascotas",
                            Precio = 8.50m,
                            ProveedoresID = 1,
                            Stock = 70
                        });
                });

            modelBuilder.Entity("PawfectMatch.Models.POS.ProductosInTabs", b =>
                {
                    b.Property<int>("ProductosInTabsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductosInTabsID"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<int>("ProductosID")
                        .HasColumnType("int");

                    b.Property<int>("VetasTabsID")
                        .HasColumnType("int");

                    b.HasKey("ProductosInTabsID");

                    b.HasIndex("ProductosID");

                    b.HasIndex("VetasTabsID");

                    b.ToTable("ProductosInTabs");

                    b.HasData(
                        new
                        {
                            ProductosInTabsID = 1,
                            IsDeleted = false,
                            Orden = 1,
                            ProductosID = 1,
                            VetasTabsID = 1
                        },
                        new
                        {
                            ProductosInTabsID = 2,
                            IsDeleted = false,
                            Orden = 2,
                            ProductosID = 2,
                            VetasTabsID = 1
                        },
                        new
                        {
                            ProductosInTabsID = 3,
                            IsDeleted = false,
                            Orden = 3,
                            ProductosID = 3,
                            VetasTabsID = 1
                        },
                        new
                        {
                            ProductosInTabsID = 4,
                            IsDeleted = false,
                            Orden = 4,
                            ProductosID = 4,
                            VetasTabsID = 1
                        },
                        new
                        {
                            ProductosInTabsID = 5,
                            IsDeleted = false,
                            Orden = 5,
                            ProductosID = 5,
                            VetasTabsID = 1
                        });
                });

            modelBuilder.Entity("PawfectMatch.Models.POS.TiposItems", b =>
                {
                    b.Property<int>("TiposItemsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TiposItemsID"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TiposItemsID");

                    b.ToTable("TiposItems");

                    b.HasData(
                        new
                        {
                            TiposItemsID = 1,
                            IsDeleted = false,
                            Nombre = "Producto"
                        },
                        new
                        {
                            TiposItemsID = 2,
                            IsDeleted = false,
                            Nombre = "Servicio"
                        });
                });

            modelBuilder.Entity("PawfectMatch.Models.POS.VetasTabs", b =>
                {
                    b.Property<int>("VetasTabsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VetasTabsID"));

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("VetasTabsID");

                    b.ToTable("VetasTabs");

                    b.HasData(
                        new
                        {
                            VetasTabsID = 1,
                            Color = "#FF5733",
                            Icono = "fas fa-home",
                            IsDeleted = false,
                            Nombre = "Inicio",
                            Orden = 1
                        });
                });

            modelBuilder.Entity("PawfectMatch.Models.Personas", b =>
                {
                    b.Property<int>("PersonasID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonasID"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EstadoCivil")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PersonasID");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("PawfectMatch.Models.PersonasRoles", b =>
                {
                    b.Property<int>("PersonasRolesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonasRolesID"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PersonasID")
                        .HasColumnType("int");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PersonasRolesID");

                    b.HasIndex("PersonasID");

                    b.ToTable("PersonasRoles");
                });

            modelBuilder.Entity("PawfectMatch.Models.Proveedores", b =>
                {
                    b.Property<int>("ProveedoresID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProveedoresID"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RNC")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ProveedoresID");

                    b.ToTable("Proveedores");

                    b.HasData(
                        new
                        {
                            ProveedoresID = 1,
                            Email = "ventas@petzone.com",
                            IsDeleted = false,
                            Nombre = "Distribuidora PetZone",
                            RNC = "132456789",
                            Telefono = "809-888-5555"
                        },
                        new
                        {
                            ProveedoresID = 2,
                            Email = "contacto@petplus.com",
                            IsDeleted = false,
                            Nombre = "PetPlus Suplidores",
                            RNC = "101112233",
                            Telefono = "809-777-4444"
                        },
                        new
                        {
                            ProveedoresID = 3,
                            Email = "info@mascotienda.com",
                            IsDeleted = false,
                            Nombre = "Mascotienda SRL",
                            RNC = "110220330",
                            Telefono = "809-666-3333"
                        });
                });

            modelBuilder.Entity("PawfectMatch.Models.Razas", b =>
                {
                    b.Property<int>("RazasID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RazasID"));

                    b.Property<int?>("EspeciesID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RazasID");

                    b.HasIndex("EspeciesID");

                    b.ToTable("Razas");

                    b.HasData(
                        new
                        {
                            RazasID = 1,
                            EspeciesID = 2,
                            IsDeleted = false,
                            Nombre = "Chihuahua"
                        },
                        new
                        {
                            RazasID = 2,
                            EspeciesID = 2,
                            IsDeleted = false,
                            Nombre = "Bulldog"
                        },
                        new
                        {
                            RazasID = 3,
                            EspeciesID = 1,
                            IsDeleted = false,
                            Nombre = "Gato Naranja"
                        });
                });

            modelBuilder.Entity("PawfectMatch.Models.RelacionSize", b =>
                {
                    b.Property<int>("RelacionSizeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RelacionSizeID"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RelacionSizeID");

                    b.ToTable("RelacionSize");

                    b.HasData(
                        new
                        {
                            RelacionSizeID = 1,
                            IsDeleted = false,
                            Nombre = "Peque�o"
                        },
                        new
                        {
                            RelacionSizeID = 2,
                            IsDeleted = false,
                            Nombre = "Mediano"
                        },
                        new
                        {
                            RelacionSizeID = 3,
                            IsDeleted = false,
                            Nombre = "Grande"
                        });
                });

            modelBuilder.Entity("PawfectMatch.Models.SeguimientoMascotas", b =>
                {
                    b.Property<int>("SeguimientoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeguimientoID"));

                    b.Property<int>("EstadoMascotaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaVista")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MascotasAdopcionID")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PersonasID")
                        .HasColumnType("int");

                    b.HasKey("SeguimientoID");

                    b.HasIndex("EstadoMascotaID");

                    b.HasIndex("MascotasAdopcionID");

                    b.HasIndex("PersonasID");

                    b.ToTable("SeguimientoMascotas");
                });

            modelBuilder.Entity("PawfectMatch.Models.Servicios.MascotasPersonas", b =>
                {
                    b.Property<int>("MascotasPersonasID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MascotasPersonasID"));

                    b.Property<int?>("EspeciesID")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PersonasID")
                        .HasColumnType("int");

                    b.Property<int?>("RazasID")
                        .HasColumnType("int");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("MascotasPersonasID");

                    b.HasIndex("EspeciesID");

                    b.HasIndex("PersonasID");

                    b.HasIndex("RazasID");

                    b.ToTable("MascotasPersonas");
                });

            modelBuilder.Entity("PawfectMatch.Models.Servicios.Servicios", b =>
                {
                    b.Property<int>("ServiciosID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiciosID"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TiposServiciosID")
                        .HasColumnType("int");

                    b.HasKey("ServiciosID");

                    b.HasIndex("TiposServiciosID");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("PawfectMatch.Models.Servicios.TiposServicios", b =>
                {
                    b.Property<int>("TiposServiciosID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TiposServiciosID"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TiposServiciosID");

                    b.ToTable("TiposServicios");

                    b.HasData(
                        new
                        {
                            TiposServiciosID = 1,
                            IsDeleted = false,
                            Nombre = "Consulta Veterinaria"
                        },
                        new
                        {
                            TiposServiciosID = 2,
                            IsDeleted = false,
                            Nombre = "Vacunaci�n"
                        });
                });

            modelBuilder.Entity("PawfectMatch.Models.SolicitudesAdopciones", b =>
                {
                    b.Property<int>("SolicitudesAdopcionesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SolicitudesAdopcionesID"));

                    b.Property<int>("EstadoSolicitudID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MascotasAdopcionID")
                        .HasColumnType("int");

                    b.Property<int>("PersonasID")
                        .HasColumnType("int");

                    b.HasKey("SolicitudesAdopcionesID");

                    b.HasIndex("EstadoSolicitudID");

                    b.HasIndex("MascotasAdopcionID");

                    b.HasIndex("PersonasID");

                    b.ToTable("SolicitudesAdopciones");
                });

            modelBuilder.Entity("PawfectMatch.Models.TipoViviendas", b =>
                {
                    b.Property<int>("TipoViviendasID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoViviendasID"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TipoViviendasID");

                    b.ToTable("TipoViviendas");

                    b.HasData(
                        new
                        {
                            TipoViviendasID = 1,
                            IsDeleted = false,
                            Nombre = "Casa"
                        },
                        new
                        {
                            TipoViviendasID = 2,
                            IsDeleted = false,
                            Nombre = "Apartamento"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PawfectMatch.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PawfectMatch.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PawfectMatch.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PawfectMatch.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PawfectMatch.Models.Adopciones.AdoptantesDetalles", b =>
                {
                    b.HasOne("PawfectMatch.Models.Personas", "Persona")
                        .WithMany("AdoptantesDetalles")
                        .HasForeignKey("PersonasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PawfectMatch.Models.TipoViviendas", "TipoVivienda")
                        .WithMany()
                        .HasForeignKey("TipoViviendasID");

                    b.Navigation("Persona");

                    b.Navigation("TipoVivienda");
                });

            modelBuilder.Entity("PawfectMatch.Models.Adopciones.HistorialAdopciones", b =>
                {
                    b.HasOne("PawfectMatch.Models.Adopciones.MascotasAdopcion", "MascotaAdopcion")
                        .WithMany()
                        .HasForeignKey("MascotasAdopcionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PawfectMatch.Models.SolicitudesAdopciones", "SolicitudAdopcion")
                        .WithMany()
                        .HasForeignKey("SolicitudesAdopcionesID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PawfectMatch.Models.SolicitudesAdopciones", null)
                        .WithMany("Historiales")
                        .HasForeignKey("SolicitudesAdopcionesID1");

                    b.Navigation("MascotaAdopcion");

                    b.Navigation("SolicitudAdopcion");
                });

            modelBuilder.Entity("PawfectMatch.Models.Adopciones.MascotasAdopcion", b =>
                {
                    b.HasOne("PawfectMatch.Models.Especies", null)
                        .WithMany("MascotasAdopcion")
                        .HasForeignKey("EspeciesID");

                    b.HasOne("PawfectMatch.Models.Estados", "Estado")
                        .WithMany("MascotasAdopcion")
                        .HasForeignKey("EstadoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PawfectMatch.Models.Razas", "Razas")
                        .WithMany("MascotasAdopcion")
                        .HasForeignKey("RazasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PawfectMatch.Models.RelacionSize", "RelacionSize")
                        .WithMany("MascotasAdopcion")
                        .HasForeignKey("RelacionSizeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Razas");

                    b.Navigation("RelacionSize");
                });

            modelBuilder.Entity("PawfectMatch.Models.Adopciones._Presentacion.PresentacionesDiapositivas", b =>
                {
                    b.HasOne("PawfectMatch.Models.Adopciones._Presentacion.Diapositivas", "Diapositiva")
                        .WithMany()
                        .HasForeignKey("DiapositivaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PawfectMatch.Models.Adopciones._Presentacion.Presentaciones", "Presentacion")
                        .WithMany("PresentacionesDiapositivas")
                        .HasForeignKey("PresentacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diapositiva");

                    b.Navigation("Presentacion");
                });

            modelBuilder.Entity("PawfectMatch.Models.Citas", b =>
                {
                    b.HasOne("PawfectMatch.Models.EstadosCitas", "EstadoCita")
                        .WithMany()
                        .HasForeignKey("EstadosCitasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PawfectMatch.Models.Servicios.MascotasPersonas", "MascotaPersona")
                        .WithMany()
                        .HasForeignKey("MascotasPersonasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PawfectMatch.Models.Personas", "Persona")
                        .WithMany("Citas")
                        .HasForeignKey("PersonasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoCita");

                    b.Navigation("MascotaPersona");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("PawfectMatch.Models.HistoriasClinicas", b =>
                {
                    b.HasOne("PawfectMatch.Models.Servicios.MascotasPersonas", "MascotaPersona")
                        .WithMany()
                        .HasForeignKey("MascotasPersonasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PawfectMatch.Models.Personas", "Veterinario")
                        .WithMany("HistoriasClinicas")
                        .HasForeignKey("PersonasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MascotaPersona");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("PawfectMatch.Models.POS.DetallesFacturas", b =>
                {
                    b.HasOne("PawfectMatch.Models.POS.Facturas", "Factura")
                        .WithMany("Detalles")
                        .HasForeignKey("FacturasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PawfectMatch.Models.POS.TiposItems", "TipoItem")
                        .WithMany("DetallesFacturas")
                        .HasForeignKey("TiposItemsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");

                    b.Navigation("TipoItem");
                });

            modelBuilder.Entity("PawfectMatch.Models.POS.Facturas", b =>
                {
                    b.HasOne("PawfectMatch.Models.POS.EstadosPagos", "EstadoPago")
                        .WithMany("Facturas")
                        .HasForeignKey("EstadoPagoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PawfectMatch.Models.Personas", "Persona")
                        .WithMany("Facturas")
                        .HasForeignKey("PersonasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoPago");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("PawfectMatch.Models.POS.Pagos", b =>
                {
                    b.HasOne("PawfectMatch.Models.POS.Facturas", "Factura")
                        .WithMany("Pagos")
                        .HasForeignKey("FacturasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("PawfectMatch.Models.POS.Productos", b =>
                {
                    b.HasOne("PawfectMatch.Models.POS.CategoriasProductos", "CategoriaProducto")
                        .WithMany()
                        .HasForeignKey("CategoriasProductosID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PawfectMatch.Models.Proveedores", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedoresID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaProducto");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("PawfectMatch.Models.POS.ProductosInTabs", b =>
                {
                    b.HasOne("PawfectMatch.Models.POS.Productos", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductosID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PawfectMatch.Models.POS.VetasTabs", "VetasTab")
                        .WithMany()
                        .HasForeignKey("VetasTabsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("VetasTab");
                });

            modelBuilder.Entity("PawfectMatch.Models.PersonasRoles", b =>
                {
                    b.HasOne("PawfectMatch.Models.Personas", "Persona")
                        .WithMany("Roles")
                        .HasForeignKey("PersonasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("PawfectMatch.Models.Razas", b =>
                {
                    b.HasOne("PawfectMatch.Models.Especies", "Especie")
                        .WithMany()
                        .HasForeignKey("EspeciesID");

                    b.Navigation("Especie");
                });

            modelBuilder.Entity("PawfectMatch.Models.SeguimientoMascotas", b =>
                {
                    b.HasOne("PawfectMatch.Models.Adopciones.EstadoMascota", "EstadoMascota")
                        .WithMany("Seguimientos")
                        .HasForeignKey("EstadoMascotaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PawfectMatch.Models.Adopciones.MascotasAdopcion", "MascotaAdopcion")
                        .WithMany()
                        .HasForeignKey("MascotasAdopcionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PawfectMatch.Models.Personas", "Persona")
                        .WithMany("Seguimientos")
                        .HasForeignKey("PersonasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoMascota");

                    b.Navigation("MascotaAdopcion");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("PawfectMatch.Models.Servicios.MascotasPersonas", b =>
                {
                    b.HasOne("PawfectMatch.Models.Especies", null)
                        .WithMany("MascotasPersonas")
                        .HasForeignKey("EspeciesID");

                    b.HasOne("PawfectMatch.Models.Personas", "Personas")
                        .WithMany("Mascotas")
                        .HasForeignKey("PersonasID");

                    b.HasOne("PawfectMatch.Models.Razas", "Razas")
                        .WithMany("MascotasPersonas")
                        .HasForeignKey("RazasID");

                    b.Navigation("Personas");

                    b.Navigation("Razas");
                });

            modelBuilder.Entity("PawfectMatch.Models.Servicios.Servicios", b =>
                {
                    b.HasOne("PawfectMatch.Models.Servicios.TiposServicios", "TipoServicio")
                        .WithMany()
                        .HasForeignKey("TiposServiciosID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoServicio");
                });

            modelBuilder.Entity("PawfectMatch.Models.SolicitudesAdopciones", b =>
                {
                    b.HasOne("PawfectMatch.Models.EstadoSolicitud", "EstadoSolicitud")
                        .WithMany("SolicitudesAdopciones")
                        .HasForeignKey("EstadoSolicitudID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PawfectMatch.Models.Adopciones.MascotasAdopcion", "MascotaAdopcion")
                        .WithMany()
                        .HasForeignKey("MascotasAdopcionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PawfectMatch.Models.Personas", "Persona")
                        .WithMany("SolicitudesAdopciones")
                        .HasForeignKey("PersonasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoSolicitud");

                    b.Navigation("MascotaAdopcion");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("PawfectMatch.Models.Adopciones.EstadoMascota", b =>
                {
                    b.Navigation("Seguimientos");
                });

            modelBuilder.Entity("PawfectMatch.Models.Adopciones._Presentacion.Presentaciones", b =>
                {
                    b.Navigation("PresentacionesDiapositivas");
                });

            modelBuilder.Entity("PawfectMatch.Models.Especies", b =>
                {
                    b.Navigation("MascotasAdopcion");

                    b.Navigation("MascotasPersonas");
                });

            modelBuilder.Entity("PawfectMatch.Models.EstadoSolicitud", b =>
                {
                    b.Navigation("SolicitudesAdopciones");
                });

            modelBuilder.Entity("PawfectMatch.Models.Estados", b =>
                {
                    b.Navigation("MascotasAdopcion");
                });

            modelBuilder.Entity("PawfectMatch.Models.POS.EstadosPagos", b =>
                {
                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("PawfectMatch.Models.POS.Facturas", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("PawfectMatch.Models.POS.TiposItems", b =>
                {
                    b.Navigation("DetallesFacturas");
                });

            modelBuilder.Entity("PawfectMatch.Models.Personas", b =>
                {
                    b.Navigation("AdoptantesDetalles");

                    b.Navigation("Citas");

                    b.Navigation("Facturas");

                    b.Navigation("HistoriasClinicas");

                    b.Navigation("Mascotas");

                    b.Navigation("Roles");

                    b.Navigation("Seguimientos");

                    b.Navigation("SolicitudesAdopciones");
                });

            modelBuilder.Entity("PawfectMatch.Models.Razas", b =>
                {
                    b.Navigation("MascotasAdopcion");

                    b.Navigation("MascotasPersonas");
                });

            modelBuilder.Entity("PawfectMatch.Models.RelacionSize", b =>
                {
                    b.Navigation("MascotasAdopcion");
                });

            modelBuilder.Entity("PawfectMatch.Models.SolicitudesAdopciones", b =>
                {
                    b.Navigation("Historiales");
                });
#pragma warning restore 612, 618
        }
    }
}
